list: $/martinimultimedia/revolution/models/slider/columns.yaml
modelClass: MartiniMultimedia\Revolution\Models\Slider
title: Sliders
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'martinimultimedia/revolution/sliders/update/:id'
